version: "3"
services:
  drdplus.loc:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=drdplus.loc"
    volumes:
      - ./www:/var/www:delegated
    entrypoint:
      - sh
      - -c
      - set -x && docker-php-ext-enable xdebug && touch /tmp/xdebug.log && chmod 0777 /tmp/xdebug.log && /bin/bash /docker.sh
    labels:
      - "traefik.backend=drdplus.loc"
      - "traefik.frontend.rule=HostRegexp: drdplus.loc,{subdomain:(.+[.])+}drdplus.loc"
      - "traefik.docker.network=docker-www"
      - "traefik.port=80"
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
