version: "3"
services:
  drdplus:
    build: .
    environment:
      PHP_IDE_CONFIG: "serverName=drdplus.loc"
      PROJECT_ENVIRONMENT: "dev"
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1 idekey=PHPSTORM remote_log=/tmp/xdebug.log"
    volumes:
      - ./www:/var/www:delegated
      - ./.docker/etc/caddy:/etc/caddy:delegated
      - ./.docker/entrypoint.sh:/entrypoint.sh:delegated
    entrypoint:
      - sh
      - -c
      - set -x && docker-php-ext-enable xdebug && touch /tmp/xdebug.log && chmod 0777 /tmp/xdebug.log && /bin/bash /entrypoint.sh
    labels:
      - "traefik.backend=drdplus"
      - "traefik.frontend.rule=HostRegexp: drdplus.loc,{subdomain:(.+[.])+}drdplus.loc"
      - "traefik.docker.network=docker-www"
    networks:
      - default
      - proxy
    restart: "no"

networks:
  proxy:
    external:
      name: docker-www
